apiVersion: apps/v1
kind: Deployment
metadata:
  name: openclaw-ollama
  labels:
    app: openclaw-ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openclaw-ollama
  template:
    metadata:
      labels:
        app: openclaw-ollama
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        {{- toYaml $.Values.nodeSelector | nindent 8 }}
      containers:
        - name: ollama
          image: ollama/ollama:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              ollama serve & pid=$!
              sleep 2
              #ollama pull qwen3.5:latest || true
              #ollama pull mistral-nemo:latest || true
              gpt-oss:latest || true
              wait $pid
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "1"
            limits:
              memory: 32Gi
              cpu: "8"
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
      volumes:
        - name: ollama-data
          hostPath:
            path: /opt/teknoir/openclaw/ollama
            type: DirectoryOrCreate
