apiVersion: v1
kind: Service
metadata:
  name: open-notebook
  labels:
    app: open-notebook
spec:
  type: NodePort
  selector:
    app: open-notebook
  ports:
    - name: ui
      port: 8502
      targetPort: 8502
      protocol: TCP
      nodePort: {{ .Values.openNotebook.nodePort }}
    - name: api
      port: 5055
      targetPort: 5055
      protocol: TCP
